name: video
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  search_page: ^2.3.0
  ellipsized_text: ^1.2.0
  equatable: ^2.0.7
  share_plus: ^10.1.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  
  visibility_detector: ^0.4.0+2
  flutter_styled_toast: ^2.2.1
  provider: ^6.1.2
  flutter_media_delete: ^1.0.1
  media_store_plus: ^0.1.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  hydrated_bloc: ^9.1.5
  shared_preferences: ^2.3.3
  device_info_plus: ^9.1.2
  list_all_videos: ^1.2.0
  path: ^1.9.0
  floating: ^5.0.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  
  image_path: "image/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "image/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "image/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "image/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - image/

